### ISSUE TITLE
how to solve no damping problem

### ISSUE THREAD

**Issue by superboy724** [toxikmango/Ongeki-Lever#1]
I successfully assembled the controller components, but there is no damping. How can I solve this problem?

**Comment by toxikmango** [comment]
Hello. Tightening the clamps around the chuck is what provides the damping. If the clamp is fully tightened and you get no added resistance to your lever it might have to do with your printer tolerances. 
You could also add thick grease, something like silicone grease might work, or if you can find it, damping grease. Years later and while I'm sure my pla printed chuck/clamp parts have slightly deformed, the controller still functions fine and I can play my usual level in game without issues. 

On the Cons&Stuff discord, there is another user in the ongeki section that made a lever design replicating the official cab hardware. You could always try that, but I found some of the parts hard to source (mainly the spring).

**Comment by superboy724** [comment]
> Hello. Tightening the clamps around the chuck is what provides the damping. If the clamp is fully tightened and you get no added resistance to your lever it might have to do with your printer tolerances. You could also add thick grease, something like silicone grease might work, or if you can find it, damping grease. Years later and while I'm sure my pla printed chuck/clamp parts have slightly deformed, the controller still functions fine and I can play my usual level in game without issues.
> 
> On the Cons&Stuff discord, there is another user in the ongeki section that made a lever design replicating the official cab hardware. You could always try that, but I found some of the parts hard to source (mainly the spring).

thanks,i just fixed this problem,my assembling method is incorrect in  4-inch pivot rod
